[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[lib]
name = "migration"
path = "src/lib.rs"


[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm-migration = "0.10.5"